name: cluster test
on: [push]
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: "1.26"

      - name: Start Redis Cluster
        uses: fujiwara/redis-cluster-action@054945eb1176310b44069966600202744e79cbc7 # v0.0.1
        id: redis
        with:
          password: testpass

      - name: cluster test
        env:
          REDIS_URL: "rediscluster://:${{ steps.redis.outputs.password }}@${{ steps.redis.outputs.host }}:${{ steps.redis.outputs.first-port }}"
        run: |
          go test -v ./...
