name: Go
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go:
          - 1.13
          - 1.14
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build & Test
      run: |
        docker run -d -p 26379:6379 redis:5
        go test -v .
