name: test
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go:
          - 1.18.5
          - 1.19
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: setup reids
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: "6.x"
          auto-start: "false"

      - name: Build & Test
        run: |
          go test -v ./...
